### ISSUE TITLE
Sprite generation error

### ISSUE THREAD

**Issue by dlip** [browniefed/compass-loader#1]
I'm on windows so maybe this is part of the issue, but when I try your library with a simple file:

```
@import "compass";
```

I get an error

```
{ [Error: ENOENT, open 'c:\images\sprite-file($map']
  errno: 34,
  code: 'ENOENT',
  path: 'c:\\images\\sprite-file($map' }
```

I'm not sure why its trying to look in c:\images, I instructed it to use a different folder for imagepath.

Using compass-mixins is working fine, even image url.

Any idea?

**Comment by browniefed** [comment]
@dlip That seems to be an issue with compass-node, I am merely supplying a pass through. That being said looking at (https://github.com/miniflycn/compass-node) it seems to say "if you don't pass anything in then use "images" directory. Which is wrong, it should just use nothing.

For `imagePath` webpack config be sure and supply an absolute path to your image directory.

Can you supply your webpack config that utilizes compass-loader? Also maybe the portion of CSS that this is breaking on? It may end up being a style that compass-node doesn't support, however with the latest node-sass 2.0 we may be able to do a re-write of compass-node to better support all of this.

**Comment by dlip** [comment]
I have made a clean example [here](https://github.com/dlip/webpack-compass-example). It's not having an error now, but its not outputting any sprite map to images folder either.

**Comment by browniefed** [comment]
Thank you for the very clear example, I don't see anything immediately incorrect with the webpack configuration. I'll pull it down and do some debugging on it later tonight and let you know.

**Comment by browniefed** [comment]
Sorry been a little swamped. Instead of `sprite-map` use `@import "images/*.png";`

**Comment by browniefed** [comment]
I'd recommend checking out the compass-node tests to see the sort of syntax it processes for sprites

**Comment by dlip** [comment]
I have gotten it working using the new import syntax, thank you for your help! The only small annoyance is that it can only find the sprites if they are outputted to the root folder `"spriteOutput=" + __dirname`

**Comment by dlip** [comment]
I have updated the repository for your reference.

**Comment by browniefed** [comment]
@dlip I believe that may be a weird issue with you using the css-loader. I don't have much experience with the css-loader and generally use the raw-loader instead.

**Comment by browniefed** [comment]
@dlip and or you need to pass httpImagePath into `compass-loader` just a few stabs in the dark at the moment.

**Comment by dlip** [comment]
@browniefed I have tried the raw-loader, but i can't change httpImagePath it always just has the sprite filename without a path. `"httpImagesPath=/images" + "&" +`. I have added my code to [this branch](https://github.com/dlip/webpack-compass-example/tree/rawloader)
