### ISSUE TITLE
String interpolation cannot be used in image-height/width function

### ISSUE THREAD

**Issue by dlip** [browniefed/compass-loader#2]
I am trying to use a variable in my mixin with image-height/width, but it seems to not be interpolating the string. The function also fails with a quoted string. It is fine with un-quoted path though.

```
height: image-height('common/sprite/' + $name + '.png');
```

```
{ [Error: ENOENT, open 'c:\Users\Dane\code\app\img\'co
mmon\sprite\' + $name + '.png'']
  errno: 34,
  code: 'ENOENT',
  path: 'c:\\Users\\Dane\\code\\app\\img\\\'common\
\sprite\\\' + $name + \'.png\'' }
```

**Comment by browniefed** [comment]
This is definitely compass-node, can you go cross post it on there (https://github.com/miniflycn/compass-node). I'll leave this open as a cross reference.
Hopefully these things get resolved with the new node-sass 2.0 and custom importers. That way we can pre-process this stuff/do less pre-processing.
